# Generated by Django 5.1.6 on 2025-02-16 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataIMC', '0003_bmi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmi',
            old_name='bmi',
            new_name='bmi_value',
        ),
    ]
