# Generated by Django 5.1.6 on 2025-02-17 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataIMC', '0004_rename_bmi_bmi_bmi_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmi_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
